package DCMS;


/**
* DCMS/CenterServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServer.idl
* Tuesday, July 11, 2017 4:40:14 PM EDT
*/

abstract public class CenterServerHelper
{
  private static String  _id = "IDL:DCMS/CenterServer:1.0";

  public static void insert (org.omg.CORBA.Any a, DCMS.CenterServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DCMS.CenterServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DCMS.CenterServerHelper.id (), "CenterServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DCMS.CenterServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CenterServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DCMS.CenterServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DCMS.CenterServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DCMS.CenterServer)
      return (DCMS.CenterServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DCMS._CenterServerStub stub = new DCMS._CenterServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DCMS.CenterServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DCMS.CenterServer)
      return (DCMS.CenterServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DCMS._CenterServerStub stub = new DCMS._CenterServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
