package DCMS;


/**
* DCMS/CenterServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServer.idl
* Saturday, July 8, 2017 3:04:58 PM EDT
*/

public interface CenterServerOperations 
{
  boolean createTRecord (String managerId, String firstName, String lastName, String address, String phone, String specialization, String location);
  boolean createSRecord (String managerId, String firstName, String lastName, String coursesRegistered, String status, String date);
  String getRecordCounts (String managerId);
  boolean editRecord (String managerId, String recordID, String fieldName, String newValue);
  boolean transferRecord (String managerId, String recordID, String remoteCenterServerName);
  void shutdown ();
} // interface CenterServerOperations
