package DCMS;


/**
* DCMS/CenterServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServer.idl
* Wednesday, July 5, 2017 10:51:52 AM EDT
*/

public interface CenterServer extends CenterServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CenterServer
