package DCMS;


/**
* DCMS/CenterServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServer.idl
* Wednesday, July 5, 2017 10:51:52 AM EDT
*/

public interface CenterServerOperations 
{
  boolean createTRecord (String managerId, String firstName, String lastName, String address, String phone, String specialization, String location);
  boolean createSRecord (String managerId, String firstName, String lastName, String coursesRegistered, String status, String date);
  String getRecordCounts (String managerId);
  void editRecord (String managerId, String recordID, String fieldName, String newValue);
  void transferRecord (String managerId, String recordID, String remoteCenterServerName);
} // interface CenterServerOperations
